Add logging
Signed-off-by: pipiland2612 <nguyen.t.dang.minh@gmail.com>

diff --git a/.github/actions/verify-metrics-snapshot/action.yaml b/.github/actions/verify-metrics-snapshot/action.yaml
--- a/.github/actions/verify-metrics-snapshot/action.yaml
+++ b/.github/actions/verify-metrics-snapshot/action.yaml
@@ -55,10 +55,15 @@ runs:
       run: |
         python3 -m pip install prometheus-client
         python3 ./scripts/e2e/compare_metrics.py --file1 ./.metrics/${{ inputs.snapshot }}.txt --file2 ./.metrics/baseline_${{ inputs.snapshot }}.txt --output ./.metrics/diff_${{ inputs.snapshot }}.txt
-        if [ $? -eq 1 ]; then
-        echo "🛑 Differences found in metrics"
-        echo "has_diff=true" >> $GITHUB_OUTPUT
-        exit 1
+        EXIT_CODE=$?
+        echo "Compare metrics exit code: $EXIT_CODE"
+        if [ $EXIT_CODE -eq 1 ]; then
+          echo "🛑 Differences found in metrics"
+          echo "has_diff=true" >> $GITHUB_OUTPUT
+          exit 1
+        else
+          echo "No differences or unexpected exit code: $EXIT_CODE"
+          exit 0  # Exit with 0 to avoid failing the step
         fi
 
     - name: Upload the diff artifact
