try-somethingelse
Signed-off-by: Yuri Shkuro <github@ysh.us>

diff --git a/.github/actions/setup-go-tip/action.yml b/.github/actions/setup-go-tip/action.yml
--- a/.github/actions/setup-go-tip/action.yml
+++ b/.github/actions/setup-go-tip/action.yml
@@ -4,40 +4,52 @@ description: 'Install Go Tip toolchain'
 runs:
   using: "composite"
   steps:
-    - name: Download Go Tip
+    # - name: Download Go Tip
+    #   id: download
+    #   shell: bash
+    #   run: |
+    #     set -euo pipefail
+    #     tip=$(git ls-remote https://github.com/golang/go.git refs/heads/master | awk '{print $1;}')
+    #     echo "Go Tip version: ${tip}"
+    #     retries=3
+    #     wait_time=10
+    #     success=false
+    #     for ((i=1; i<=retries; i++)); do
+    #       url="https://storage.googleapis.com/go-build-snap/go/linux-amd64/${tip}.tar.gz"
+    #       if curl -fsSL -o gotip.tar.gz "$url"; then
+    #         success=true
+    #         break
+    #       fi
+    #       echo "Failed to download. Retrying in $wait_time seconds..."
+    #       sleep $wait_time
+    #     done
+    #     echo "success=${success}" >> $GITHUB_OUTPUT
+
+    # - name: Unpack gotip bundle
+    #   if: steps.download.outputs.success == 'true'
+    #   shell: bash
+    #   run: |
+    #     echo Unpack gotip bundle
+    #     set -euo pipefail
+    #     echo "Downloaded bundle:"
+    #     ls -lah gotip.tar.gz
+    #     export GOROOT="$HOME/sdk/gotip"
+    #     mkdir -p $GOROOT
+    #     tar -C $GOROOT -xzf gotip.tar.gz
+    #     echo "GOROOT=$GOROOT" >> $GITHUB_ENV
+
+    - name: Download pre-built Go tip from grafana/gotip repo
       id: download
       shell: bash
       run: |
-        echo Download Go Tip
-        set -euo pipefail
-        tip=$(git ls-remote https://github.com/golang/go.git refs/heads/master | awk '{print $1;}')
-        echo "Go Tip version: ${tip}"
-        retries=3
-        wait_time=10
-        success=false
-        for ((i=1; i<=retries; i++)); do
-          url="https://storage.googleapis.com/go-build-snap/go/linux-amd64/${tip}.tar.gz"
-          if curl -fsSL -o gotip.tar.gz "$url"; then
-            success=true
-            break
-          fi
-          echo "Failed to download. Retrying in $wait_time seconds..."
-          sleep $wait_time
-        done
-        echo "success=${success}" >> $GITHUB_OUTPUT
-
-    - name: Unpack gotip bundle
-      if: steps.download.outputs.success == 'true'
-      shell: bash
-      run: |
-        echo Unpack gotip bundle
-        set -euo pipefail
-        echo "Downloaded bundle:"
-        ls -lah gotip.tar.gz
+        gh release download ubuntu-latest --repo grafana/gotip --pattern 'go*.zip'
+        unzip go.zip -d $HOME/sdk
         export GOROOT="$HOME/sdk/gotip"
-        mkdir -p $GOROOT
-        tar -C $GOROOT -xzf gotip.tar.gz
         echo "GOROOT=$GOROOT" >> $GITHUB_ENV
+        # echo "GOPATH=$HOME/go" >> "$GITHUB_ENV"
+        # echo "$HOME/go/bin" >> "$GITHUB_PATH"
+        # echo "$HOME/sdk/gotip/bin" >> "$GITHUB_PATH"
+        echo "success=${success}" >> $GITHUB_OUTPUT
 
     # If download failed, we will try to build tip from source.
     # This requires Go toolchain, so install it first.
